steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '.']
  id: 'BuildImage'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}']
  id: 'PushImage'
  waitFor: ['BuildImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-central1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']



  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-central1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-east1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-east4
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=europe-west1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=europe-west2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-east1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-east2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-northeast1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-northeast2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-west2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-west3
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=us-west4
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=northamerica-northeast1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=southamerica-east1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=europe-west3
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=europe-west6
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=europe-central2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=australia-southeast1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-south1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-southeast1
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-southeast2
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - run
  #     - deploy
  #     - proxyrequest
  #     - --no-allow-unauthenticated
  #     - --region=asia-northeast3
  #     - --source=.
  #     - --timeout=540
  #     - --memory=128Mi
