steps:
  # HTTP triggers
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-west1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-east1)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-east4)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=europe-west1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=europe-west2
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-east1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-east2)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-northeast1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-northeast2
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-west2)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-west3 City)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=us-west4)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=northamerica-northeast1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=southamerica-east1)
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=europe-west3
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=europe-west6
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=europe-central2
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=australia-southeast1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-south1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-southeast1
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-southeast2
      - --source=.
      - --trigger-http
      - --timeout=3600
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - proxyrequest
      - --entry-point=HandleProxyRequest
      - --gen2
      - --runtime=$_RUNTIME
      - --region=asia-northeast3
      - --source=.
      - --trigger-http
      - --timeout=3600

substitutions:
  _RUNTIME: go116
