steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '.']
  id: 'BuildImage'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}']
  id: 'PushImage'
  waitFor: ['BuildImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-central1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-west1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-east1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-east4', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-west1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-west2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-east1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-east2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-northeast1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-northeast2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-west2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-west3', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'us-west4', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'northamerica-northeast1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'southamerica-east1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-west3', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-west6', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-central2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'australia-southeast1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-south1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-southeast1', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-southeast2', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '--region', 'asia-northeast3', '--platform', 'managed', '--no-allow-unauthenticated', "--memory", "128Mi", "--timeout", "540"]
  waitFor: ['PushImage']
